In [21]:
!pip install bing-image-downloader

In [22]:
!ls

In [23]:
cd /content/drive/My Drive/Colab Notebooks/machine learning (actual)

/content/drive/My Drive/Colab Notebooks/machine learning (actual)


In [24]:
!ls

'Copy of ML - Intro_Linear.pptx'  'LINEAR REGRESS.ipynb'
 FRUIT.ipynb			  'mini project.ipynb'
 HOMEWORK-images.ipynb		  'preprocessing of image.ipynb'
 images				   Underweight-knn.csv
'INTRO TO IMAGE data.ipynb'	   Underweight-knn.gsheet
 K-NEIGHNOURS.ipynb		  'using logistic ,tree for the images .ipynb'


In [25]:
!mkdir images

mkdir: cannot create directory ‘images’: File exists


In [26]:
cd images

/content/drive/My Drive/Colab Notebooks/machine learning (actual)/images


In [27]:
from bing_image_downloader import downloader
downloader.download("dog",limit=20,output_dir="images")



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Pastor_vasco_m_14months_loby_3018.jpg/1200px-Pastor_vasco_m_14months_loby_3018.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.ytimg.com/vi/vlfiKbrZgvg/hqdefault.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Chaser_the_BC%2C_snow_full_body.jpg/1200px-Chaser_the_BC%2C_snow_full_body.jpg
[Error]Invalid image, not saving https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Chaser_the_BC%2C_snow_full_body.jpg/1200px-Chaser_the_BC%2C_snow_full_body.jpg

[!] Issue getting: https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Chaser_the_BC%2C_snow_full_body.jpg/1200px-Chaser_the_BC%2C_snow_full_body.jpg
[!] Error:: No active exception to reraise
[%] Downloading Image #3 from https://i.ytimg.com/vi/KOI4JJFZlu0/hqdefault.jpg
[%] File Downloaded !

[%] Downloading Image

In [28]:
from bing_image_downloader import downloader
downloader.download("cat",limit=20,output_dir="images")



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://i.ytimg.com/vi/UwtTSqTbWzg/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.ytimg.com/vi/ZakV2xtqqMM/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://upload.wikimedia.org/wikipedia/commons/d/dc/Grumpy_Cat_%2814556024763%29_%28cropped%29.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.ytimg.com/vi/XLFqNc0_Dp8/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.ytimg.com/vi/zPCZWn_iWb0/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://2.bp.blogspot.com/-wNG9jajTdTk/T9d7gtvm4mI/AAAAAAAANOY/X5eZH3wqkNs/s1600/funny-cat-pictures-part-2-06-13-2012-016.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://i.ytimg.com/vi/4YMw

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import glob
from PIL import Image
import cv2
import os


for i in glob.glob("/content/drive/My Drive/Colab Notebooks/machine learning (actual)/images/images/dog/*.jpg"):
  b=cv2.imread(i)
  print(b.shape)

(1800, 1200, 3)
(360, 480, 3)
(360, 480, 3)
(720, 1280, 3)
(360, 480, 3)
(720, 1280, 3)
(1286, 1200, 3)
(720, 1280, 3)
(360, 480, 3)
(960, 720, 3)
(360, 480, 3)
(360, 480, 3)
(360, 480, 3)
(720, 1280, 3)
(360, 480, 3)
(720, 1280, 3)
(720, 1280, 3)
(1800, 1200, 3)
(360, 480, 3)
(360, 480, 3)


In [29]:
from skimage.io import imread
from skimage.transform import resize
import numpy as np


target = []   # This is the list of Target Output
flat_data = []   # Image pixel in flatten style
images= []

path='/content/drive/My Drive/Colab Notebooks/machine learning (actual)/images/images/'
for dirpath, dirnames, filenames in os.walk(path):
  for filename in filenames:
    category = dirpath.split('/')[-1]
    target.append(category)
    img = imread(f'{path}{category}/{filename}')
    img_resized = resize(img,(50,50,3))  # Scaling down   this is alredy resized and normalixed
    flat_data.append(img_resized.flatten())
    images.append(img_resized)

#PUTTING INTO THE NUMPY ARRAY
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

print(flat_data.shape)
print(target.shape)
print(images.shape)


(40, 7500)
(40,)
(40, 50, 50, 3)


In [30]:
target

array(['dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog',
       'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog',
       'dog', 'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat',
       'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat',
       'cat', 'cat', 'cat', 'cat'], dtype='<U3')

In [31]:
import pandas as pd
df=pd.DataFrame(flat_data)
df.head()

0         1         2     ...      7497      7498      7499
0  0.169608  0.249020  0.219608  ...  0.807843  0.600000  0.217647
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3  0.215686  0.164706  0.219608  ...  0.300784  0.218431  0.223529
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[5 rows x 7500 columns]

In [32]:
df['target']=target
df.head()

0         1         2         3  ...      7497      7498      7499  target
0  0.169608  0.249020  0.219608  0.156863  ...  0.807843  0.600000  0.217647     dog
1  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000     dog
2  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000     dog
3  0.215686  0.164706  0.219608  0.219608  ...  0.300784  0.218431  0.223529     dog
4  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000     dog

[5 rows x 7501 columns]

In [193]:
x=df.drop(columns=['target'])
y=df['target']

In [194]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape


((30, 7500), (10, 7500), (30,), (10,))

In [195]:
#y_test

**Applying Kneighbours classifier**

In [196]:
#USING NEIGHBOURS sqrt of rows (manually calculating the n_neighbours)
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=6)
model.fit(x_train,y_train)
pred=model.predict(x_test)
pred

array(['dog', 'cat', 'cat', 'cat', 'cat', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [197]:
import numpy as np
a=np.array(y_test)
a

array(['cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [198]:
#y_test

In [199]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       0.67      0.80      0.73         5
         dog       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[4 1]
 [2 3]]


# aplying gridsearchcv 

In [203]:
z = np.arange(1,25)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [204]:
from sklearn.model_selection import GridSearchCV
param={'n_neighbors':z}   #LET US DEFINE A DICTIONARY
model = KNeighborsClassifier()
model_grid = GridSearchCV(model,param)   #ITS TAKES 2 PARAMETRS 
#LIKE IT TELLS TO 'model' to TAKE PARAM AS 'Z',SO WE WRITEEN {'n_neighbors':z}  ,AND STORES IN 'model_grid '
model_grid.fit(x_train,y_train)


GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [205]:
model_grid.best_params_

{'n_neighbors': 8}

In [206]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=8)
model.fit(x_train,y_train)
pred=model.predict(x_test)
pred

array(['cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'dog', 'dog',
       'dog'], dtype=object)

# Applying classification report and confusion matrix

In [207]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       0.80      0.80      0.80         5
         dog       0.80      0.80      0.80         5

    accuracy                           0.80        10
   macro avg       0.80      0.80      0.80        10
weighted avg       0.80      0.80      0.80        10

[[4 1]
 [1 4]]


#applying logistic regression

In [213]:
from sklearn.linear_model import LogisticRegression as LR
m=LR(class_weight='balanced')
m.fit(x_train,y_train)
pred=m.predict(x_test)
pred

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array(['dog', 'cat', 'dog', 'dog', 'cat', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [214]:
a

array(['cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [215]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       0.75      0.60      0.67         5
         dog       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[3 2]
 [1 4]]


# applying decesion tree classifier

In [216]:
from sklearn.tree import DecisionTreeClassifier as DTC
mod=DTC(class_weight='balanced')
mod.fit(x_train,y_train)
pred=mod.predict(x_test)
pred

array(['dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog',
       'dog'], dtype=object)

In [217]:
a

array(['cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [218]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       1.00      0.20      0.33         5
         dog       0.56      1.00      0.71         5

    accuracy                           0.60        10
   macro avg       0.78      0.60      0.52        10
weighted avg       0.78      0.60      0.52        10

[[1 4]
 [0 5]]


**Applying support vector machine**

In [219]:
from sklearn import svm
mod=svm.SVC()
mod.fit(x_train,y_train)
pred=mod.predict(x_test)

pred

array(['dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [220]:
a

array(['cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [221]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       0.67      0.80      0.73         5
         dog       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[4 1]
 [2 3]]


# Applying random forrest classifier

In [222]:
from sklearn.ensemble import RandomForestClassifier as RFC
m=RFC()
m.fit(x_train,y_train)
pred=m.predict(x_test)
pred_prob=m.predict_proba(x_test)
print(pred)
print(pred_prob)

['dog' 'cat' 'cat' 'dog' 'cat' 'dog' 'cat' 'dog' 'dog' 'cat']
[[0.43 0.57]
 [0.57 0.43]
 [0.55 0.45]
 [0.42 0.58]
 [0.54 0.46]
 [0.45 0.55]
 [0.62 0.38]
 [0.39 0.61]
 [0.12 0.88]
 [0.5  0.5 ]]


In [223]:
a

array(['cat', 'cat', 'cat', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog',
       'cat'], dtype=object)

In [224]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

         cat       0.80      0.80      0.80         5
         dog       0.80      0.80      0.80         5

    accuracy                           0.80        10
   macro avg       0.80      0.80      0.80        10
weighted avg       0.80      0.80      0.80        10

[[4 1]
 [1 4]]
